$schema: https://json.schemastore.org/circleciconfig#
version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:16.13.0
jobs:
  checks:
    executor: node
    steps:
      - checkout
      - run:
          name: Add .npmrc
          command: printf "@datacamp:registry=https://registry.npmjs.org/\n//registry.npmjs.org/:_authToken=$NPM_TOKEN\n" > .npmrc
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Check commitlint
          command: yarn commitlint:ci
      - run:
          name: Lint
          command: yarn lint
workflows:
  pr_flow:
    jobs:
      - checks:
          context: org-global
          filters:
            branches:
              ignore:
                - main
